version: "3.9"
services:
    web:
        container_name: app
        build: 
            dockerfile: BitcoinPricePresenter/Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - db
        hostname: bitcoin-presenter
    db:
        container_name: db
        hostname: mssql1
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "v3ryStr0ngP@ss"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - /var/opt/mssql